# Generated by Django 3.2.6 on 2021-08-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videoMetadata',
            fields=[
                ('videoId', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('publishedAt', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('thumbnailUrl', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
